export const OPEN_MODAL_EDIT = "OPEN_MODAL_EDIT";
export const CLOSE_MODAL_EDIT = "CLOSE_MODAL_EDIT";
export const OPEN_MODAL_ADD = "OPEN_MODAL_ADD";
export const CLOSE_MODAL_ADD = "CLOSE_MODAL_ADD";
export const OPEN_MODAL_REMOVE = "OPEN_MODAL_REMOVE";
export const CLOSE_MODAL_REMOVE = "CLOSE_MODAL_REMOVE";
export const OPEN_MODAL_CATEGORY_SAVING_ADD = "OPEN_MODAL_CATEGORY_SAVING_ADD";
export const CLOSE_MODAL_CATEGORY_SAVING_ADD =
  "CLOSE_MODAL_CATEGORY_SAVING_ADD";
export const OPEN_MODAL_CATEGORY_INCOME_ADD = "OPEN_MODAL_CATEGORY_INCOME_ADD";
export const CLOSE_MODAL_CATEGORY_INCOME_ADD =
  "CLOSE_MODAL_CATEGORY_INCOME_ADD";
export const OPEN_MODAL_CATEGORY_EXPENSE_ADD =
  "OPEN_MODAL_CATEGORY_EXPENSE_ADD";
export const CLOSE_MODAL_CATEGORY_EXPENSE_ADD =
  "CLOSE_MODAL_CATEGORY_EXPENSE_ADD";
